### ISSUE TITLE
Evernote Import Fails Silently

### ISSUE THREAD

**Issue by geekmuse** [paperwork/paperwork#13] opened 2014-12-01 00:59 UTC
Hi,

First off, thanks for such an excellent project -- I think it's great, much-needed, and highly desirable for folks who love the Evernote concept but don't want someone else holding all of their data for them.

I've installed the latest release on my own server (CentOS 6.5), gotten it stood up, and everything seems to be running well.  I've exported my Evernote ENEX file and tried importing it, which seems to be silently failing.  All permissions seem to be set appropriately as I can create a new note and add an attachment, larevel.log is present in 'logs', et. al.  Whenever I try to import the file, the settings page refreshes with the 'Language' tab as active and the 'User Interface Language' element and associated dropdown being colored in red.  I even tried changing the ENEX file's extension to 'xml' thinking that might be the issue, but still no dice.  The ENEX export file is only 89K -- certainly not large enough to violate any php.ini constraints, so I don't think that is the issue, either.

Neither laravel.log or my httpd's error_log seem to have anything pertaining to an error in them.

Thanks again for a great product,
Brad

**Comment by JamborJan** [comment] 2015-07-22 06:09
Hi guys, I have been working on the import feature for the Sandstorm package of Paperwork (see: https://github.com/JamborJan/paperwork/issues/17).

I have also realized that some files can be imported and some not. I will try to debug this a bit more and find a solution. I would guess that it has something to do with special signs. Tests show that big files (in my case I allow up to 100MB) are not an issue.

**Comment by JamborJan** [comment] 2015-07-23 06:07
I have been experimenting with the Evernote import a bit, from my point of view this is the status:
- The import fails often due to random reasons
- Files are too big (depends on your nginx / php config)
- Notes content has special things (maybe, no evidence found)

Additionally there would be some useful improvements for the Evernote Import:
- Display upload progress (needed especially for big files)
- Display a proper message when file is to big (if possible upfront)

Let me know if I should file new issues for these or if we can track them here. I will try to continue working on those.

**Comment by Baldrs** [comment] 2015-07-23 07:28
It also may be written in an memory-inefficient way, so import may be hitting memory_limit on the larger files.

**Comment by solprov** [comment] 2016-01-26 16:07
Hi, is it possible to import notes from tomboy to Paperwork?

**Comment by JamborJan** [comment] 2016-01-26 17:48
Hi @solprov 

It would only work when this application can export data in the special Evernote XML format.

If not an import feature must be implemented. Can you please create a new issue for that? Please add as many information as you have e.g. a link to the apps website, source code if it is open source and if available export file examples.

**Comment by artin-phares** [comment] 2016-08-10 08:17
Hey, Evernote is on last month before new free-account rules will take place (2 devices only). So it would be nice to prepare for this and leave anywhere. But I have 4K notes in Evernote, so I cannot just leave and start from scratch. I need to export/import somewhere.
Is there any progress on import feature? This work is highly appreciated.

**Comment by Liongold** [comment] 2016-08-10 15:42
The import should work well. You can try it. If you encounter any issues, please open a new one.

**Comment by artin-phares** [comment] 2016-08-10 17:48
@Liongold Yep, tried and failed. Going to file new one.

**Comment by JamborJan** [comment] 2016-08-10 19:38
FYI: i did some improvements which have never been merged: https://github.com/twostairs/paperwork/commit/da082a88583de8e2c946a3c3bd0fa6aa44803a54

I am using the changes productive in the Sandstorm.io port of paperwork. It's working better but not 100 percent. But it has a better error handling and the user at least knows what the cause of a failed import is.

I can recommend to create chunks of export files and import them as file size is an issue with the current way how the importer works.

Hope this input helps.

JJ

**Comment by Liongold** [comment] 2016-08-15 12:48
Can you merge those changes to the official version? Or are they specific to Sandstorm?

**Comment by Liongold** [comment] 2016-08-15 12:50
Actually, they seem to be present in both the develop and master branches.

**Closed** 2019-05-03 14:16 UTC
Labels: 1, enhancement
